# Site settings / variables
title: Evan Lindsey
email: evan@evanlindsey.net
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.evanlindsey.net" # the base hostname & protocol for your site, e.g. http://example.com\
github_username:  evanlindsey
logo_url: "https://avatars3.githubusercontent.com/u/8053238"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-coffeescript
